GET  http://localhost:3000/api/string/compare HTTP/1.1
content-type: application/json

###

POST http://localhost:3000/api/string/compare HTTP/1.1
content-type: application/json

{
    "referenceString": "Head Linx",
    "stringToCompare": "Gama Moto"
}